<a href="https://colab.research.google.com/github/ctrl-scott/CS6647/blob/main/owen_cs6647_homework1_huan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Use sympy to solve the following questions**
**1. Solve the quadratic function $x^2+2x-8=0$**

In [2]:
from sympy import *

In [3]:
#https://docs.sympy.org/latest/guides/solving/solve-equation-algebraically.html
#according to the website the fact that any expression not using the Eq (equation) 
#is automatically assumed to equal zero (0) by the solving functions
from sympy import solve, Symbol
x = Symbol('x')
expr = (x**2+2*x-8)
print(solve(expr, dict=True))


[{x: -4}, {x: 2}]


**2. What is the function f(x) which is equal to its
derivative?**

In [4]:
from sympy import Function, Symbol
f = symbols('f', cls=Function)
Derivative.diff(f(x))


Derivative(f(x), x)

**3. Compute the area under $f(x)=x^3$ from x=0 to x=1**

In [5]:
import sympy
#Define symbols
x0,x1 = sympy.symbols("x0,x1")
x0=0
x1=1
f=x**3
f
sympy.limit(f,x0,x1)




x**3

**4. Calculate $\displaystyle\sum\limits_{x=0}^\infty \left(\frac{1}{x!}\right)$**

In [6]:
from sympy.abc import i, k, m, n, x
from sympy import Sum, factorial, oo, IndexedBase, Function
#(1/x!) = 1
expr = Sum(1/(x**-1),(x,0,sympy.oo))
expr

Sum(x, (x, 0, oo))

**5. Calculate $\lim_{n \rightarrow \infty}(1+\frac{1}{n})^n$**

In [7]:
#sympy.limit(function, variable, value)
sympy.limit(1/n,1,sympy.oo)
symbols = 'n'
expr = 1/n
sympy.limit(expr,n,sympy.oo)



0

**6. flips the matrix through its diagonal $\begin{bmatrix}2&-3&-8&7 \\-2&-1&2&-7\\ 1&0&-3&6 \end{bmatrix}$**

In [8]:
A = Matrix ([
    [2, -3, -8, 7],
    [-2, -1, 2, -7],
    [1, 0, -3, 6]])
display(A)

transpose(A)


Matrix([
[ 2, -3, -8,  7],
[-2, -1,  2, -7],
[ 1,  0, -3,  6]])

Matrix([
[ 2, -2,  1],
[-3, -1,  0],
[-8,  2, -3],
[ 7, -7,  6]])

**7. Row operations: We know the following matrix**

In [9]:
 M = eye(3)
 M

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

**Do matrix row operations to R2 ← R2 + 3R1. (update Row 2 to R2+3*R1). Print the matrix**

In [10]:
from sympy.interactive.printing import init_printing
#https://docs.sympy.org/latest/modules/matrices/matrices.html
init_printing(use_unicode=False, wrap_line=False)
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt

M = Matrix([[1,0,0], [0,1,0], [0,0,1]]); M
MU = M.row(1)+(3*(M.row(1)))
M = Matrix([[1,0,0], MU, [0,0,1]]) ; M



[1  0  0]
[       ]
[0  4  0]
[       ]
[0  0  1]

**8.Find determinant of M**

In [11]:
#determinant in sympy is sympy M.det if M = Matrix []
from sympy.interactive.printing import init_printing
#https://docs.sympy.org/latest/modules/matrices/matrices.html
init_printing(use_unicode=False, wrap_line=False)
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt

M = Matrix([[1,0,0], [0,1,0], [0,0,1]]); M
MU = M.row(1)+(3*(M.row(1)))
M = Matrix([[1,0,0], MU, [0,0,1]]) ; M
M.det()


4

**9.Find the following matrix's eigenvalue and eigen vector**

In [24]:
M = Matrix( [[ 9, -2],
[-2, 6]] )

M.eigenvals()




{5: 1, 10: 1}

In [25]:
M = Matrix( [[ 9, -2],
[-2, 6]] )

M.eigenvects()

         [1/2]             [-2]   
[(5, 1, [[   ]]), (10, 1, [[  ]])]
         [ 1 ]             [1 ]   

**10. Implement the Predator-prey model in python**

Suppose fish starts at 10 hundreds, bears starts at 1 hundred

alpha = 1.1

beta = 0.4

delta = 0.1

gamma = 0.4

draw the plots(bear-time, fish-time)

t = np.linspace(0,50,num=1000)


In [37]:
#https://scientific-python.readthedocs.io/en/latest/notebooks_rst/3_Ordinary_Differential_Equations/02_Examples/Lotka_Volterra_model.html
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import integrate
import ipywidgets as ipw

alpha = 1.1
beta = 0.4
delta = 0.1
gamma = 0.4
x0 = 0.0010
y0 = 0.001

def draw_the_plots(X, t, alpha, beta, delta, gamma):
    x, y = X
    dotx = x * (alpha - beta * y)
    doty = y * (-delta + gamma * x)
    return np.array([dotx, doty])
  
#num as Nt
Nt = 1000
#tmax as 50
tmax = 50
t = np.linspace(0,tmax, Nt)
X0 = [x0, y0]
res = integrate.odeint(draw_the_plots, X0, t, args = (alpha, beta, delta, gamma))
x, y = res.T

#I can print(x,y) and get results. Not sure what I was doing wrong.
print(x,y)


#I tried to use this portion, but it didn't show --
# I got this from the link in Modules, Lecture

plt.figure()
plt.grid()
plt.title("odeint method")
plt.plot(t, x, 'xb', label = 'Fish')
plt.plot(t, y, '+r', label = "Bear")
plt.xlabel('Time t, [days]')
plt.ylabel('Population')
plt.legend()

plt.show()





[ 1.00000000e-03  1.05658509e-03  1.11637319e-03  1.17953014e-03
  1.24625862e-03  1.31677212e-03  1.39127491e-03  1.46999479e-03
  1.55316793e-03  1.64104688e-03  1.73389543e-03  1.83199647e-03
  1.93564783e-03  2.04516354e-03  2.16087580e-03  2.28313657e-03
  2.41231643e-03  2.54880485e-03  2.69301578e-03  2.84538729e-03
  3.00637839e-03  3.17648060e-03  3.35620692e-03  3.54610168e-03
  3.74674278e-03  3.95873631e-03  4.18272211e-03  4.41937961e-03
  4.66942689e-03  4.93362335e-03  5.21277048e-03  5.50771328e-03
  5.81934499e-03  6.14860868e-03  6.49650377e-03  6.86408453e-03
  7.25246297e-03  7.66281590e-03  8.09638908e-03  8.55449540e-03
  9.03852109e-03  9.54993519e-03  1.00902882e-02  1.06612149e-02
  1.12644452e-02  1.19018101e-02  1.25752401e-02  1.32867734e-02
  1.40385648e-02  1.48328942e-02  1.56721692e-02  1.65589340e-02
  1.74958768e-02  1.84858359e-02  1.95318114e-02  2.06369723e-02
  2.18046674e-02  2.30384367e-02  2.43420187e-02  2.57193622e-02
  2.71746394e-02  2.87122

<IPython.core.display.Javascript object>