<a href="https://colab.research.google.com/github/ctrl-scott/CS6647/blob/main/owen_CS6647_homework5_huan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#From Module 6 Lecture Markov Chains
#https://www.youtube.com/watch?v=i3AkTO9HLXo
#https://www.youtube.com/watch?v=G7FIQ9fXl6U

import numpy as np
import sympy

state = {
    0: "Rest",
    1: "Sweeties",
    2: "Exercises"
}

state

{0: 'Rest', 1: 'Sweeties', 2: 'Exercises'}

In [ ]:
A = np.array([[0.2,0.2,0.6],[0.1,0.2,0.7],[0.6,0.1,0.3]])
A

array([[0.2, 0.2, 0.6],
       [0.1, 0.2, 0.7],
       [0.6, 0.1, 0.3]])

In [ ]:
n = 15
start_state = 0
print(state[start_state], "--->", end=" ")
prev_state = start_state

while n-1:
  curr_state = np.random.choice([0,1,2],p=A[prev_state])
  print(state[curr_state], "--->", end=" ")
  prev_state = curr_state
  n-=1
print("stop")

Rest ---> Sweeties ---> Exercises ---> Exercises ---> Rest ---> Exercises ---> Exercises ---> Rest ---> Sweeties ---> Exercises ---> Exercises ---> Rest ---> Sweeties ---> Exercises ---> Exercises ---> stop


In [ ]:
steps = 10**4
start_step = 0
pi = np.array([0,0,0])
pi[start_state] = 1
prev_state = start_state

i = 0
while i < steps:
  curr_state = np.random.choice([0,1,2], p=A[prev_state])
  pi[curr_state]+=1
  prev_state = curr_state
  i += 1

print("pi = ", pi/steps)

pi =  [0.3684 0.1583 0.4734]


In [ ]:
#stationary distribution
steps = 1
A_n = A

i=0
while i<steps:
  A_n = np.matmul(A_n,A)
  i+=1

  print("A^n = \n", A_n, "\n")
  print("pi = ", A_n[0])

A^n = 
 [[0.42 0.14 0.44]
 [0.46 0.13 0.41]
 [0.31 0.17 0.52]] 

pi =  [0.42 0.14 0.44]
